Avoid re-emitting docgen for re-exported components
rspack-contrib/storybook-rsbuild pull request #9
Opened 2024-05-23 05:07 UTC by wrose504

In our codebase we will often define a component in one file, then re-export it from `index.ts`. In some cases, the re-export uses a name that does not match the original component. In these cases, `react-docgen-loader` emits invalid code that tries to assign docgen info to the actual name from the original component, which fails.

    // components/Button/Button.tsx
    import React from 'react';
    export const Button = () => (<button type='submit'/>);
    export default Button;
    
    // components/Button/index.ts
    import ButtonComponent from './Button';
    export default ButtonComponent;

    // components/Bouton/index.ts
    import {Button as Bouton} from '../Button/Button';
    export {Bouton};
   
    // App.tsx
    import Button from './components/Button';
    import Bouton from './components/Bouton';
    
    const App = () => (
      <form><Button/><Bouton/></form>
    );

Currently invalid code is written into `components/Button/index.ts` and `components/Bouton/index.ts` that tries to assign to `Button.__docgenInfo`, when `Button` is not a valid identifier in either file.

The `react-webpack` implementation of `react-docgen-loader` avoids this problem by checking that the resolved component definition comes from the initial source file. See https://github.com/storybookjs/storybook/blob/e812f77def55aa7aeda70dddcc378c736412472d/code/presets/react-webpack/src/loaders/react-docgen-loader.ts#L25

This PR adds the same logic here, which fixes the issue.

2024-05-23 10:18 UTC, fi3ework requested changes

2024-05-23 10:18 UTC, fi3ework commented on sandboxes/react-rsbuild/src/stories/Bouton.ts
> +import { Button as Bouton } from './Button'
```suggestion
import { Button } from './Button'
```

2024-05-23 10:18 UTC, fi3ework commented on sandboxes/react-rsbuild/src/stories/Bouton.stories.ts
> +  title: 'Example/Bouton',
I think better to rename the new added story's title and file name to `ReExportButton` to help demonstrating its purpose.

2024-05-23 10:19 UTC, fi3ework commented
Thanks for the sync up with storybook's latest code. 🫶

2024-05-23 18:29 UTC, wrose504 commented on sandboxes/react-rsbuild/src/stories/Bouton.ts
> +import { Button as Bouton } from './Button'
This is necessary to demonstrate the problem: if we just import `Button` named as it is, the generated code will not fail. I will update it to import as `ReExportButton` as you suggested.

2024-05-24 03:47 UTC, fi3ework approved these changes

2024-05-24 03:48 UTC, merged

2024-05-24 03:48 UTC, fi3ework commented
Thanks you!